[package]
name = "hello_conrod"
version = "0.1.0"
authors = ["mHALr <ryo97321@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conrod_glium = "0.68.0"
glium = "0.25.0"
