[package]
name = "snakegame"
version = "0.1.0"
authors = ["mHALr <ryo97321@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
piston_window = "0.105.0"